CREATE OR REPLACE TRIGGER Notify_Grade_Change
AFTER UPDATE OF MARKS, GRADE ON GRADES
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Grade updated for Student ID: ' || :NEW.STUDENT_ID || 
                        ', New MARKS: ' || :NEW.MARKS || ', New GRADE: ' || :NEW.GRADE);
END;
/

UPDATE GRADES SET MARKS=77,GRADE='B' WHERE STUDENT_ID=3107;