--1) STUDENT TABLE
CREATE TABLE STUDENT(
    STUDENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    DATE_OF_BIRTH DATE,
    EMAIL VARCHAR2(20)
);

--2) COURSES TABLE
CREATE TABLE COURSES(
    COURSE_ID NUMBER PRIMARY KEY,
    COURSE_NAME VARCHAR2(15),
    START_DATE DATE,
    END_DATE DATE,
    CREDIT NUMBER
);

--3) GRADES TABLE
CREATE TABLE GRADES(
    GRADE CHAR(3),
    MARKS NUMBER,
    STUDENT_ID NUMBER,
    COURSE_ID NUMBER,
    FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY(COURSE_ID) REFERENCES COURSES(COURSE_ID)
);
